services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: radiology-oracle
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: OraclePass123
      APP_USER: radiology_user
      APP_USER_PASSWORD: RadiologyPass123
    volumes:
      - radiology-oracle-data:/opt/oracle/oradata

volumes:
  radiology-oracle-data: